import ROOT



filediRecoMC = ROOT.TFile("twomuonsRecoPtHist_mc.root")
filediGenMC = ROOT.TFile("twomuonsGenPtHist_mc.root")
c2 = ROOT.TCanvas("c2","Muon Pt",200,10,700,500)
TwoMuonRecoPt = filediRecoMC.Get("twomuonsRecoPtHist")
TwoMuonGenPt = filediGenMC.Get("twomuonsGenPtHist")
TwoMuonGenPt.SetLineColor(ROOT.kGreen)
TwoMuonGenPt.SetFillColor(ROOT.kGreen)
TwoMuonGenPt.SetFillStyle(3001)
TwoMuonRecoPt.SetLineColor(ROOT.kViolet)
TwoMuonRecoPt.SetFillColor(ROOT.kViolet)
TwoMuonRecoPt.SetFillStyle(3001)
TwoMuonRecoPt.Draw()
TwoMuonGenPt.Draw("sames")
leyMuons = ROOT.TLegend(0.4,0.6,0.89,0.89)
leyMuons.SetFillColor(ROOT.kWhite)
leyMuons.AddEntry(TwoMuonGenPt,"Pt Gen Muons","f")
leyMuons.AddEntry(TwoMuonRecoPt,"Pt Reco Muons","f")
leyMuons.Draw()
c2.SaveAs("twomuonsPtHist_Reco_vs_Gen.root")
c2.cd()




fileJDiRecoMC = ROOT.TFile("jetsDiRecoPtHist_mc.root")
fileJDiGenMC = ROOT.TFile("jetsDiGenPtHist_mc.root")
c3 = ROOT.TCanvas("c3","Jets Pt Gen/Reco",200,10,700,500)
JetsDiRecoPt = fileJDiRecoMC.Get("jetsDiRecoPtHist")
JetsDiGenPt = fileJDiGenMC.Get("jetsDiGenPtHist")
JetsDiGenPt.SetLineColor(ROOT.kGreen)
JetsDiGenPt.SetFillColor(ROOT.kGreen)
JetsDiGenPt.SetFillStyle(3004)
JetsDiRecoPt.SetLineColor(ROOT.kBlue)
JetsDiRecoPt.SetFillColor(ROOT.kBlue)
JetsDiRecoPt.SetFillStyle(3005)
JetsDiGenPt.Draw()
JetsDiRecoPt.Draw("sames")
leyJets = ROOT.TLegend(0.4,0.6,0.89,0.89)
leyJets.SetFillColor(ROOT.kWhite)
leyJets.AddEntry(JetsDiGenPt,"Pt Gen Jets","f")
leyJets.AddEntry(JetsDiRecoPt,"Pt Reco Jets","f")
leyJets.Draw()
c3.SaveAs("jetsDiPtHist_Reco_vs_Gen.root")
c3.cd()




filemassMC = ROOT.TFile("massdistdimuonsHist_mc.root")
filemassJMC = ROOT.TFile("massjetdistdimuonsHist_mc.root")
c4 = ROOT.TCanvas("c4","JMass distribution",200,10,700,500)
Massdist = filemassMC.Get("massdistdimuonsHist")
Massjetdist = filemassJMC.Get("massjetdistdimuonsHist")

scale = 1/Massdist.Integral()
Massdist.Scale(scale)
scale = 1/Massjetdist.Integral()
Massjetdist.Scale(scale)

Massjetdist.SetLineColor(ROOT.kRed)
Massjetdist.SetFillColor(ROOT.kRed)
Massjetdist.SetFillStyle(3001)
Massdist.SetLineColor(ROOT.kGreen)
Massdist.SetFillColor(ROOT.kGreen)
Massdist.SetFillStyle(3001)
Massdist.Draw()
Massjetdist.Draw("sames")
leyMass = ROOT.TLegend(0.4,0.6,0.89,0.89)
leyMass.SetFillColor(ROOT.kWhite)
leyMass.AddEntry(Massdist,"Matched Jets","f")
leyMass.AddEntry(Massjetdist,"WRONG Comb. Jets","f")
leyMass.Draw()
c4.SaveAs("massHist_Matched_vs_NotMatched.root")
c4.cd()



filebjetsDiscriminatorMC = ROOT.TFile("bjetsDiscriminatorHist_mc.root")
filequarkjetsDiscriminatorMC = ROOT.TFile("quarksjetsDiscriminatorHist_mc.root")
c5 = ROOT.TCanvas("c5","Discriminator Values",200,10,700,500)
bjetsDiscriminator = filebjetsDiscriminatorMC.Get("bjetsDiscriminatorHist")
quarksjetsDiscriminator = filequarkjetsDiscriminatorMC.Get("quarksjetsDiscriminatorHist")

scale=1/bjetsDiscriminator.Integral()
bjetsDiscriminator.Scale(scale)
scale=1/quarksjetsDiscriminator.Integral()
quarksjetsDiscriminator.Scale(scale)

bjetsDiscriminator.SetLineColor(ROOT.kGreen)
bjetsDiscriminator.SetFillColor(ROOT.kGreen)
bjetsDiscriminator.SetFillStyle(3004)
quarksjetsDiscriminator.SetLineColor(ROOT.kBlue)
quarksjetsDiscriminator.SetFillColor(ROOT.kBlue)
quarksjetsDiscriminator.SetFillStyle(3005)
quarksjetsDiscriminator.Draw()
bjetsDiscriminator.Draw("sames")
leydisc = ROOT.TLegend(0.4,0.6,0.89,0.89)
leydisc.SetFillColor(ROOT.kWhite)
leydisc.AddEntry(bjetsDiscriminator,"b-Jets","f")
leydisc.AddEntry(quarksjetsDiscriminator,"qq(W)-Jets","f")
leydisc.Draw()
c5.SaveAs("discriminatorvalues_bquarks_Wquarks.root")
c5.cd()



filedeltaRMuonsMC = ROOT.TFile("deltaRdimuonsHist_mc.root")
filedeltaRJetsMC = ROOT.TFile("deltaRjetsdimuonsHist_mc.root")
c6 = ROOT.TCanvas("c6","Discriminator Values",200,10,700,500)
deltaRMuonsMC = filedeltaRMuonsMC.Get("deltaRdimuonsHist")
deltaRJetsMC  = filedeltaRJetsMC.Get("deltaRjetsdimuonsHist")
deltaRMuonsMC.SetLineColor(ROOT.kGreen+3)
deltaRMuonsMC.SetFillColor(ROOT.kGreen+3)
deltaRMuonsMC.SetFillStyle(3001)
deltaRJetsMC.SetLineColor(ROOT.kBlue+3)
deltaRJetsMC.SetFillColor(ROOT.kBlue+3)
deltaRJetsMC.SetFillStyle(3001)
deltaRJetsMC.Draw()
deltaRMuonsMC .Draw("sames")
leydR = ROOT.TLegend(0.4,0.6,0.89,0.89)
leydR.SetFillColor(ROOT.kWhite)
leydR.AddEntry(deltaRMuonsMC,"DeltaR Muons","f")
leydR.AddEntry(deltaRJetsMC,"DeltaR Jets","f")
leydR.Draw()
c6.SaveAs("deltaR_Muons_and_Jets.root")
c6.cd()

fileResMuonsMC = ROOT.TFile("resPtdimuonsHist_mc.root")
fileResJetsMC = ROOT.TFile("resPtjetsdimuonsHist_mc.root")
c7 = ROOT.TCanvas("c7","Discriminator Values",200,10,700,500)
ResMuonsMC = fileResMuonsMC.Get("resPtdimuonsHist")
ResJetsMC  = fileResJetsMC.Get("resPtjetsdimuonsHist")
ResMuonsMC.SetLineColor(ROOT.kGreen+1)
ResMuonsMC.SetFillColor(ROOT.kGreen+1)
ResMuonsMC.SetFillStyle(3001)
ResJetsMC.SetLineColor(ROOT.kBlue-3)
ResJetsMC.SetFillColor(ROOT.kBlue-3)
ResJetsMC.SetFillStyle(3001)
ResJetsMC.Draw()
ResMuonsMC.Draw("sames")
leydRes = ROOT.TLegend(0.4,0.6,0.89,0.89)
leydRes.SetFillColor(ROOT.kWhite)
leydRes.AddEntry(ResMuonsMC,"Res Muons","f")
leydRes.AddEntry(ResJetsMC,"Res Jets","f")
leydRes.Draw()
c7.SaveAs("res_Muons_and_Jets.root")
c7.cd()








fileRecoMC = ROOT.TFile("jetsRecoPtHist_mc.root")
fileGenMC = ROOT.TFile("jetsGenPtHist_mc.root")
c8 = ROOT.TCanvas("c8","Jets Pt",200,10,700,500)
JetsRecoPt = fileRecoMC.Get("jetsRecoPtHist")
JetsGenPt = fileGenMC.Get("jetsGenPtHist")
JetsGenPt.SetLineColor(ROOT.kBlue+10)
JetsGenPt.SetFillColor(ROOT.kBlue+10)
JetsGenPt.SetFillStyle(3001)
JetsRecoPt.SetLineColor(ROOT.kBlue+3)
JetsRecoPt.SetFillColor(ROOT.kBlue+3)
JetsRecoPt.SetFillStyle(3001)
JetsRecoPt.Draw()
JetsGenPt.Draw("sames")
leyJets = ROOT.TLegend(0.4,0.6,0.89,0.89)
leyJets.SetFillColor(ROOT.kWhite)
leyJets.AddEntry(JetsGenPt,"Pt Gen Jets","f")
leyJets.AddEntry(JetsRecoPt,"Pt Reco Jets","f")
leyJets.Draw()
c8.SaveAs("jetsPtHist_Reco_vs_Gen.root")
c8.cd()


fileRecoMC = ROOT.TFile("muonsRecoPtHist_mc.root")
fileGenMC = ROOT.TFile("muonsGenPtHist_mc.root")
c9 = ROOT.TCanvas("c9","Muon Pt",200,10,700,500)
JetsRecoPt = fileRecoMC.Get("muonsRecoPtHist")
JetsGenPt = fileGenMC.Get("muonsGenPtHist")
JetsGenPt.SetLineColor(ROOT.kGreen+3)
JetsGenPt.SetFillColor(ROOT.kGreen+3)
JetsGenPt.SetFillStyle(3001)
JetsRecoPt.SetLineColor(ROOT.kGreen+10)
JetsRecoPt.SetFillColor(ROOT.kGreen+10)
JetsRecoPt.SetFillStyle(3001)
JetsGenPt.Draw()
JetsRecoPt.Draw("sames")
leyJets = ROOT.TLegend(0.4,0.6,0.89,0.89)
leyJets.SetFillColor(ROOT.kWhite)
leyJets.AddEntry(JetsGenPt,"Pt Gen Muons","f")
leyJets.AddEntry(JetsRecoPt,"Pt Reco Muons","f")
leyJets.Draw()
c9.SaveAs("muonsPtHist_Reco_vs_Gen.root")
c9.cd()
